const data = [
  {
    id: "a",
    src: "/images/vincent-van-zalinge-bird.jpg",
    alt: "A tiny shrewd turquoise-and-amber bird",
    tags: [
      "bird",
      "blurred background",
      "wildlife",
      "animal in its natural habitat",
    ],
  },
  {
    id: "b",
    src: "/images/alexandru-rotariu-dog.jpg",
    alt: "A serious-looking grey dog with cool glacier eyes",
    tags: ["dog", "HD"],
  },
  {
    id: "c",
    src: "/images/scott-walsh-fox.jpg",
    alt: "A happy-looking cute wild fox in nature, near some pink flowers",
    tags: ["fox", "flowers"],
  },
  {
    id: "d",
    src: "/images/andy-holmes-giraffe.jpg",
    alt: "A giraffe sticking its black tongue out",
    tags: ["giraffe", "dramatic"],
  },
  {
    id: "e",
    src: "/images/karsten-winegeart-dog.jpg",
    alt: 'A small dog wearing a golden "Champions" hoodie',
    tags: ["dog", "cute", "animal wearing human clothes"],
  },
  {
    id: "f",
    src: "/images/marko-blazevic-cat.jpg",
    alt: "A small kitten standing on its back legs, reaching up towards the camera",
    tags: ["kitten", "cat", "#cute"],
  },
  {
    id: "g",
    src: "/images/mark-stoop-lizard.jpg",
    alt: "A relaxed green lizard, sitting on a wooden beam",
    tags: ["lizard", "world-famous insurance salesman from the commercials"],
  },
  {
    id: "h",
    src: "/images/geran-de-klerk-squirrel.jpg",
    alt: "A fuzzy squirrel, highlighted in a dark backdrop",
    tags: ["squirrel", "animal", "fuzzy"],
  },
  {
    id: "i",
    src: "/images/wexor-tmg-turtle.jpg",
    alt: "A large tropical turtle swimming in water",
    tags: ["turtle", "ocean", "flippers"],
  },
  {
    id: "j",
    src: "/images/animal-11.jpg",
    alt: "My doggo, Simba, and my cat, Kiara, looking majestic",
    tags: ["dog", "cat", "HD"],
  },
  {
    id: "k",
    src: "/images/animal-12.jpg",
    alt: "My doggo, Kovu, looking majestic",
    tags: ["dog", "HD"],
  },
  {
    id: "l",
    src: "/images/animal-13.jpg",
    alt: "Cocodrile",
    tags: ["cocodrile", "animal", "reptile"],
  },
  {
    id: "m",
    src: "/images/animal-14.jpg",
    alt: "Bird",
    tags: ["bird", "nature"],
  },
  {
    id: "n",
    src: "/images/animal-15.jpg",
    alt: "Iguana",
    tags: ["iguana", "nature"],
  },
  {
    id: "o",
    src: "/images/animal-16.jpg",
    alt: "Tiger",
    tags: ["tiger", "zoo"],
  },
  {
    id: "p",
    src: "/images/animal-17.jpg",
    alt: "Tortoise",
    tags: ["tortoise", "zoo"],
  },
  {
    id: "q",
    src: "/images/animal-18.jpg",
    alt: "Gorilla",
    tags: ["gorilla", "zoo", "nature"],
  },
  {
    id: "r",
    src: "/images/animal-19.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "s",
    src: "/images/animal-5.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "t",
    src: "/images/animal-6.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "u",
    src: "/images/animal-7.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "v",
    src: "/images/animal-8.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "w",
    src: "/images/animal-9.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
  {
    id: "x",
    src: "/images/animal-10.jpg",
    alt: "My doggo, Zuhur, looking majestic",
    tags: ["dog", "photo"],
  },
];

export default data;
